### PR TITLE
Starting point for UI

### PR DESCRIPTION
**Pull request by aniwng**
Are you guys ok with the UI being under ./webapp?

- Just adding a starting foundation for the UI. (https://github.com/facebook/create-react-app)
- React as framework. (https://reactjs.org)

### CODE REVIEW

**Comment by romeara** [comment]
Project name: 

I think in general we are going for a two-level name structure: `<layer>.<specific>`. The layer part groups projects into things of the same architectural layer (domain, database, interface, etc). The second differeniates the projects. So for the "main" UI, maybe "interface.web"?

Second, no idea if we had any plans to use a specific framework or things - in the past, we used thymeleaf (because it integrated incredibly well with spring boot and the backend), and I know JavaScript by itself is also a thing. 

@nickavv , did you or @emilyford352 have any preferences or thoughts on direction for that? Just wanted to ask now, before we get too far into it.

**Review by nickavv — APPROVED** [review]
@romeara I like Thymeleaf for the templating because it does work well with Spring. But for the frontend code I'm not opposed to React (I love learning new things!)
We just need to make sure we find out how to make it play nice with the backend @aniwng

**Comment by nickavv** [comment]
As far as `webapp` vs `interface.web` interface might be too vague (could mean java interfaces or something.) How about `ui.web` or `ui.webapp`?

**Comment by romeara** [comment]
Sure, `ui.web` meets the criteria just fine, lets go with that unless @aniwng wants to make a case for otherwise. 

And yeah, true - the only criteria for the UI framework stuff is "plays well with stuff we choose for the backend". @aniwng - so as long as it seems to be a common use case to have it interact in with a Java/REST backend, we can use whatever - we just don't want to be forcing/hacking anything to do something it isn't meant to, that way lies madness :P

**Comment by aniwng** [comment]
Okay, let's go with `ui.web`.

@romeara @nickavv React will play nice with a REST backend. Only thing we need to think of is how to build and run the full stack. We could have backend and frontend on separate servers and use ngnix to handle the proxying. Not a blocker now, but something to think about!

**Review by romeara — APPROVED** [review]
Looks good, project is named and this looks ready to roll!

**Pull request merged**
